---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - name: helloworld
        {{ if .Values.image }}
        image: "warrelucky/go-hello-http:{{ .Values.image.tag }}"
        {{ else }}
        image: "warrenlucky/go-hello-http:{{ .Chart.AppVersion }}"
        {{ end }}
        ports:
        - containerPort: 8080
