---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://35.232.78.23
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: go-hello-http
    repoURL: https://github.com/warrenlucky/gitops-argocd
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
