---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld-tiexin2
  namespace: argotest
spec:
  destination:
    namespace: default
    server: https://34.68.185.208
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
      - values.tiexin2.yaml
    path: go-hello-http
    repoURL: https://github.com/warrenlucky/gitops-argocd.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

